### ISSUE TITLE
doesnt work in multiplayer??? (idk)

### ISSUE THREAD

**Issue by Nagatka** [aNaOH/LethalHelper#1]
There are 2 mods lethal helper and lethal drones (dependent mod lethal helper). I don't know which mod has the problem, but since only lethal helper has a file on github so I decided to ask here. If other players pick up an item from the lethal drones mod, they will not be able to drop it or interact with anything at all. And the host has no problems. I don't know if the problem is with your mod or if you are the creator of the lethal drones mod. But uhhh

**Comment by aNaOH** [comment]
Oh! I'll check it. And yeah, both mods are mine, Lethal Helper is a library I made to add scrap without modifying the code which I made for Lethal Drones

**Comment by aNaOH** [comment]
Ok! Bug found, networking stuff it seems. I'm going to see how to fix it, when the update is released, i'll comment and close the issue.

**Comment by aNaOH** [comment]
@Nagatka fixed!
It may take a while to be updated at Thunderstore and at the mod managers. The correct versions are:

- LethalHelper 1.0.2
- LethalDrones 1.0.512
